### ISSUE TITLE
maxspeed:advisory=130 although no motorway

### ISSUE THREAD

**Issue by karussell** [westnordost/osm-legal-default-speeds#10]
For

```
junction=roundabout
highway=tertiary
rural=yes
```

I get: 

```
maxspeed:advisory=130
...
```

Is this a bug?

Please note that I do not get this tagging in the wild but I provide "rural=yes" in the replacerFn as
`(name, eval) -> eval.invoke() || "rural".equals(name)`

**Comment by westnordost** [comment]
Ref: 

https://westnordost.github.io/osm-legal-default-speeds/#tags=junction%3Droundabout%0Ahighway%3Dtertiary%0Arural%3Dyes&cc=DE

Indeed, this is a bug! But is it a bug in the source data or in the lib?
