### ISSUE TITLE
Provide method to check if OSM tag is used or return list of involved tags

### ISSUE THREAD

**Issue by karussell** [westnordost/osm-legal-default-speeds#11]
See discussion [here](https://github.com/graphhopper/graphhopper/commit/06548921f6e74900121743920f999bcf5eecd9da#commitcomment-114745800):

> Alternatively, we could add a new method to the default speed limits library that outputs all tags used by the currently loaded legal speed limits, so that no maintenance of this functionality is needed.

A method might be a bit better suited as one could also test if tag "startsWith" a certain string etc.

**Comment by westnordost** [comment]
True

El 26 de mayo de 2023 10:05:49 CEST, Peter ***@***.***> escribió:
>See discussion [here](https://github.com/graphhopper/graphhopper/commit/06548921f6e74900121743920f999bcf5eecd9da#commitcomment-114745800):
>
>> Alternatively, we could add a new method to the default speed limits library that outputs all tags used by the currently loaded legal speed limits, so that no maintenance of this functionality is needed.
>
>A method would be better suited as one could also test if tag "startsWith" a certain string etc.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/osm-legal-default-speeds/issues/11
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
