### ISSUE TITLE
Handle `source:maxspeed=DE:zone*` or `maxspeed:type=DE:zone*`

### ISSUE THREAD

**Issue by tordans** [westnordost/osm-legal-default-speeds#4]
In Germany, I noticed that some data has a source-tag but no explicit `maxspeed` tag. 

This is the case for the value `DE:rural` (or urban) which are supported by the app for both variants
- `source:maxspeed` https://westnordost.github.io/osm-legal-default-speeds/#tags=highway%3Dresidential%0Asource%3Amaxspeed%3DDE%3Arural&cc=DE
- `maxspeed:type` https://westnordost.github.io/osm-legal-default-speeds/#tags=highway%3Dresidential%0Amaxspeed%3Atype%3DDE%3Arural&cc=DE

However, there is also a "zone" schema, that is not yet supported. In the time I invested to look into this I did not figure out why there are so many different ways to describe the same information (as far as I can tell), but I found multiple combinations of key and value with "zone" in it.

Taginfo:

- `source:maxspeed` => search for 'zone' in the search filed https://taginfo.openstreetmap.org/keys/source%3Amaxspeed#values
- `maxspeed:type` => search for 'zone' in the search filed https://taginfo.openstreetmap.org/keys/maxspeed:type#values

Examples from the app:

- `maxspeed:type=DE:zone20` does not work https://westnordost.github.io/osm-legal-default-speeds/#tags=highway%3Dresidential%0Amaxspeed%3Atype%3DDE%3Azone20&cc=DE
- `source:maxspeed=DE:zone:20` does not work https://westnordost.github.io/osm-legal-default-speeds/#tags=highway%3Dresidential%0Asource%3Amaxspeed%3DDE%3Azone%3A20&cc=DE
- `source:maxspeed=DE:zone30` does not work https://westnordost.github.io/osm-legal-default-speeds/#tags=highway%3Dresidential%0Asource%3Amaxspeed%3DDE%3Azone30&cc=DE

There are some more variants in https://github.com/FixMyBerlin/osm-scripts/blob/main/utils/Highways-MaxspeedData/utils/addMaxspeedProperty.ts or https://github.com/FixMyBerlin/osm-scripts/blob/main/utils/Highways-MaxspeedData/utils/addMaxspeedSourceProperty.ts#L61-L73.

---

Suggestions on what to do with this…

- Add a list of unsupported special cases to the readme (with link on the demo page)
- Add support for those special cases

---

PS: I hope, at some point someone will take the time to cleanup that tagging mess …

**Comment by westnordost** [comment]
`DE:zone30` does not define an unsigned legal speed limit though, hence, interpreting this tag is out of scope of the "Default speed limits" wiki page and thus also this library:

It is signed, even explicitly with the proper maxspeed sign. According to taginfo, 99.64% of all roads tagged with `DE:zone30` have a `maxspeed=30` tagged, so if this explicit tag is missing, it really can be considered a tagging error..

**Comment by westnordost** [comment]
> PS: I hope, at some point someone will take the time to cleanup that tagging mess …

Also, you forgot `zone:maxspeed=DE:30` and `zone:traffic=DE:zone30` 🤣

**Comment by tordans** [comment]
Thanks for you input, westnordost! I agree with that. Also, your talk at SOTM 2022 helped to understand the tool more completely https://2022.stateofthemap.org/sessions/YWH3XD/
