### ISSUE TITLE
Performance tuning

### ISSUE THREAD

**Issue by karussell** [westnordost/osm-legal-default-speeds#7]
[We tried to integrate the library into GraphHopper](https://github.com/graphhopper/graphhopper/blob/157810014ed067537bae552c9b621626490055a2/core/src/main/java/com/graphhopper/routing/util/parsers/DefaultMaxSpeedParser.java#L38-L44) but we are currently facing a rather big slow down. E.g. for [this PBF](https://download.geofabrik.de/europe/germany/sachsen-latest.osm.pbf) we normally have an import time of around 23sec and with the latest integration this takes ~60-70s. For planet PBF the slow down exists too but the bigger problem in these cases are the memory errors like `GC overhead limit exceeded` that don't go away even with 20GB more RAM.

As the GC seems to be very active it could be also the reason for the slow down but I'm unsure as although I gave it several GBs it wasn't faster. I also tried to reduce the regex compilations with a cache but without success.

What only helped was to avoid calling limitSpeedsTo. For that [I replaced createResultTags](https://github.com/karussell/osm-legal-default-speeds/commit/b46b1244afa7f0a4901dded42f2a3d3d5da13a37#diff-b941eb401f6dd6e078345017abbf535560bc896d8f86e6e5a546d290424a3902L134) with:

```kotlin
if (exactRoadType != null) {
  val result = exactRoadType.tags.toMutableMap()
  result.putAll(tags.filter { !it.isImplicitMaxSpeed })
  return Result(exactRoadType.name, result, Certitude.Exact)
}
```

Is it possible to make calling this optional? The reduction of the other speeds is not really needed in our case as we would reduce it ourselves via Math.min which would be simpler+faster. (Or maybe do this only when fetched from the map but a custom map implementation would be necessary)

[I tried to avoid the pattern matching and used indexOfs instead](https://github.com/karussell/osm-legal-default-speeds/commit/b46b1244afa7f0a4901dded42f2a3d3d5da13a37#diff-b941eb401f6dd6e078345017abbf535560bc896d8f86e6e5a546d290424a3902R236) and the improvement was significant but not enough for us (only down to 33sec).

**Comment by westnordost** [comment]
Do you have a benchmark result, i.e. how much time was spent in which functions? 

I see a few places that maybe could be optimized, namely the new instance creation of the Regexes (or the use of the regexes altogether) and the copying of lists and maps. But it would be preliminary optimization without seeing if it actually matters.

---

`limitSpeedsTo` is not optional, otherwise the library would output for input of e.g. 

```
maxspeed=60
highway=motorway
```
e.g. an HGV speed like this
```
maxspeed:hgv=100
```
(because the legislation says that a HGV may not go faster than 100, but that also means that it may not go faster than any general speed limit posted; the mentioned function guarantees that).

The requirement of this library is certainly to be correct, so I don't think we can refrain from doing that.

**Comment by westnordost** [comment]
> [I tried to avoid the pattern matching and used indexOfs instead](https://github.com/karussell/osm-legal-default-speeds/commit/b46b1244afa7f0a4901dded42f2a3d3d5da13a37#diff-b941eb401f6dd6e078345017abbf535560bc896d8f86e6e5a546d290424a3902R236) and the improvement was significant but not enough for us (only down to 33sec).

That's nice, though. Please feel free to create a PR for that already. (One thing after another.)

**Comment by westnordost** [comment]
What would probably somewhat speed up the results for large input data - independent of any performance optimizations within this library - would be to cache the results. I.e. have a map like
```
// Map<input tags, result>
Map<Map<String, String>, LegalDefaultSpeeds.Result>
```
and only calculate it if not already present in the map.

The memory hog-ness of such a cache could be somewhat reduced if only the tags on the way relevant to default speed limits would be considered.

**Comment by westnordost** [comment]
Is it maybe the conditionals-stuff that takes this long?

**Comment by westnordost** [comment]
Actually, regarding the cache: One can just use a (large) LRU cache to guarantee it to not exceed a certain memory limit and the most common taggings are memorized.

**Comment by westnordost** [comment]
I've just replaced the creation of a list and removing elements from there with doing the same with a sequence. Let me know if it makes any difference.

**Comment by westnordost** [comment]
Regarding the conditionals stuff, the current situation is a bit awkward:

The Python parser of the wiki page outputs speed limits in the JSON like this:
```json
"tags": {
  "maxspeed": "100",
  "maxspeed:goods": "80",
  "maxspeed:goods:conditional": "70 @ (weightrating>3.5); 60 @ (weightrating>12)",
},
```

only for the kotlin library having to pull apart and glue back together these values again in the `limitSpeedsTo` function.

It may be easier to consume if the output of the JSON generator would be e.g. something like this (or similar):

```json
"tags": {
  "maxspeed": {
    "speed": "100"
  },
  "maxspeed:goods": {
    "speed": "80",
    "conditionals": [
      {"speed": "70", "condition": "weightrating>3.5" },
      {"speed": "60", "condition": "weightrating>12" },
    ]
  },
},
```

However, the only thing that would saved would be 

- the splitting of the string by "; "
- the splitting of the substring by " @ "

So, not sure if this does really make such a difference, given to change this one has to both change the python script and also the kotlin library parsing it.

**Comment by westnordost** [comment]
So, how much of this overhead is the splitting of strings with ; and @?

**Comment by westnordost** [comment]
Ah, I see. I'd imagine that creating another hashmap for every single road instead of modifying the input map could be a source of overhead.

Something like
```
fun getRoadType(
        countryCode: String,
        tags: Map<String, String>,
        relationsTags: List<Map<String, String>> = emptyList(),
        replacerFn: (name: String, evaluate: () -> Boolean) -> Boolean = { _, ev -> ev() }
    ): AnotherResult?
```

where AnotherResult would contain the certitude, the matched road type name and the "raw" tags associated with that road type.

--- 

But uhm, as I wrote, a lru cache that caches the results associated by their input values (output for the same input values will be the same, after all) will solve any performance issues.

**Comment by otbutz** [comment]
You could use [async-profiler](https://github.com/async-profiler/async-profiler) to track CPU usage and memory allocations.

**Comment by westnordost** [comment]
That a cache has very little effect or even a negative effect really puzzles me... how can effectively not calling the library (i.e. only call it for uniques) be about as fast as calling the library?

Though, that the key of your cache is a string is a little suspect. Might be a bit costly to create a string from each and every tags of each and every road segment. I'd have created a data structure with `hashCode` that'd contain the tags map, country alpha2.

**Comment by westnordost** [comment]
Yes, but the String concatenation is avoidable.

**Comment by otbutz** [comment]
JMC also provides a solid automated analysis which might help here :)

https://www.oracle.com/java/technologies/javase/products-jmc8-downloads.html

**Comment by westnordost** [comment]
I see you already did! Some notes:

> btw: would you be able to release a new version?

Could do, need to check if I have the keys with me (I'm traveling right now) 

>>  So, the string splitting does make a difference after all?

> You mean master vs. 1.2? Have not tested it and always used master since then.

No, I mean the splitting of the strings done here

https://github.com/westnordost/osm-legal-default-speeds/blob/1554cc5a5d0c20d2bd71b1dcfa92cbab3acd6172/library/src/commonMain/kotlin/de/westnordost/osm_legal_default_speeds/LegalDefaultSpeeds.kt#L237-L240

which would be avoidable if the JSON was changed like here suggested here https://github.com/westnordost/osm-legal-default-speeds/issues/7#issuecomment-1558760541
